version: '3.9'
services:
  backend:
    hostname: localhost

    depends_on:
      database:
        condition: service_healthy

    restart: always

    build:
      context: products
      dockerfile: Dockerfile

    environment:
      DEBUG: ${DEBUG}
      PROJECT_NAME: ${PROJECT_NAME}
      SERVER_NAME: ${SERVER_NAME}

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

    ports:
      - "80:8080"
    volumes:
      - ./products:/products
    privileged: true
    command: bash -c "alembic upgrade head && python main.py"

  database:
    image: postgres:14.3
    volumes:
      - ./database/data2:/var/lib/postgresql/data
      - ./database/backups2:/backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}

    restart: always